/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Item;
import model.Servico;

/**
 *
 * @author Victor
 */
public class TelaAddServicos extends javax.swing.JDialog {

    /**
     * Creates new form TelaAddServicos
     */
    String[] arrayS;
    ArrayList<Servico> servicoCliente;
    ArrayList<Servico> servicoHotel;
    DefaultListModel lModelC;
    DefaultListModel lModelH;

    public TelaAddServicos(java.awt.Frame parent, boolean modal, ArrayList<Item> array) {
        super(parent, modal);
        DefaultListModel lModelH = new DefaultListModel();
        DefaultListModel lModelC = new DefaultListModel();
        this.lModelC = lModelC;
        this.lModelH = lModelH;
        ArrayList<String> arrayS = new ArrayList<>();
        servicoHotel = new ArrayList<>();
        servicoCliente = new ArrayList<>();

        int i = 0;
        for (Item item : array) {
            if (item instanceof Servico) {
                i++;
                arrayS.add(item.getDescricao());
                servicoHotel.add((Servico) item);

            }

        }
        this.arrayS = arrayS.toArray(new String[i]);


        initComponents();
        jListCliente.setModel(lModelC);
        jListHotel.setModel(lModelH);

        for (Servico servico : servicoHotel) {
            lModelH.addElement(servico.getDescricao());
        }

    }

    public TelaAddServicos(java.awt.Frame parent, boolean modal, ArrayList<Item> array,ArrayList<Servico> arrayServ) {
        super(parent, modal);

        DefaultListModel lModelH = new DefaultListModel();
        DefaultListModel lModelC = new DefaultListModel();
        this.lModelC = lModelC;
        this.lModelH = lModelH;
        ArrayList<String> arrayS = new ArrayList<>();
        servicoHotel = new ArrayList<>();
        servicoCliente = new ArrayList<>();

        int i = 0;
        for (Item item : array) {
            if (item instanceof Servico) {
                i++;
                arrayS.add(item.getDescricao());
                servicoHotel.add((Servico) item);

            }

        }
        this.arrayS = arrayS.toArray(new String[i]);
        for (String s : this.arrayS) {
            System.out.println(s);
            System.out.println("asdd");
        }

        initComponents();
        jListCliente.setModel(lModelC);
        jListHotel.setModel(lModelH);

        for (Servico servico : servicoHotel) {
            lModelH.addElement(servico.getDescricao());
        }
        if(arrayServ!=null){
        for(Servico servico : arrayServ){
            lModelC.addElement(servico.getDescricao());
            servicoCliente.add(servico);
        }}
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCliente = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListHotel = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jListCliente);

        jListHotel.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings =arrayS ;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListHotel);

        jButton1.setText("Requisitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Serviços Requisitados");

        jLabel3.setText("Serviços do Hotel");

        jButton2.setText("<<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Retirar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane3)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addGap(143, 143, 143))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = jListHotel.getSelectedIndex();
        if (i > -1) {
            servicoCliente.add(servicoHotel.get(jListHotel.getSelectedIndex()));

            lModelC.addElement(lModelH.getElementAt(i));
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = jListCliente.getSelectedIndex();
        if (i > -1) {
            lModelC.remove(i);
            servicoCliente.remove(i);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    ArrayList<Servico> showDialog() {
        setVisible(true);
        return servicoCliente;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jListCliente;
    private javax.swing.JList<String> jListHotel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
